# Colors (Iceberg Light)
[colors.bright]
black = '0x8389a3'
blue = '0x22478e'
cyan = '0x327698'
green = '0x598030'
magenta = '0x6845ad'
red = '0xcc3768'
white = '0x262a3f'
yellow = '0xb6662d'

[colors.normal]
black = '0xdcdfe7'
blue = '0x2d539e'
cyan = '0x3f83a6'
green = '0x668e3d'
magenta = '0x7759b4'
red = '0xcc517a'
white = '0x33374c'
yellow = '0xc57339'

[colors.primary]
background = '0xe8e9ec'
foreground = '0x33374c'

