cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'neovim/neovim'

#==============================================================================
# Command-Line
#==============================================================================
brew 'gpg'
brew 'ctags'
brew 'coreutils'
brew 'openssl'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'zsh'
brew 'keybase'
brew 'neovim/neovim/neovim'
brew 'git'
brew 'git-lfs'
brew 'node'
brew 'lua'
brew 'python3'
brew 'python'
brew 'rbenv'
brew 'ruby-build'
brew 'thefuck'
brew 'youtube-dl'
brew 'mas'

#==============================================================================
# Applications
#==============================================================================
# Web Browsers
cask 'google-chrome'
cask 'iterm2'
cask 'sequel-pro'
cask 'android-studio'
cask 'filezilla'
cask 'slack'
cask 'discord'
cask 'postbox'
cask 'textual'
cask 'spotify'
cask 'the-unarchiver'
cask 'istat-menus'
cask 'subler'
cask 'android-file-transfer'
cask 'keepingyouawake'
cask 'flux'
cask 'cleanmymac'
cask '1password'
cask 'java'
cask 'vlc'
cask 'virtualbox'
cask 'dropbox'
cask 'imageoptim'
