" ------------------------------------------
" Guide from
" http://blog.tjll.net/yet-another-vim-setup/
" -------------------------------------------

" NOTE: DEFAULT LEADER KEY IS '\'

" -------------------
" ENABLE VUNDLE PLUGINS
" -------------------
" Setup Vundle package manager
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'             " Shows the git branch in airline and adds some features
Plugin 'scrooloose/nerdtree'
Plugin 'mattn/emmet-vim'
Plugin 'Shougo/neocomplete.vim'         " Auto completion plugin that doesn't crash in sudo :)
Plugin 'kien/ctrlp.vim'
Plugin 'airblade/vim-gitgutter'         " Adds git diff icons to the gutter

" Colourschemes
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'scwood/vim-hybrid'
Plugin 'gregsexton/Atom'
Plugin 'juanedi/predawn.vim'

call vundle#end()
filetype plugin indent on


" -----------------
" BASIC SETTINGS
" ----------------
set hidden                                                      " Hides buffers
set nocompatible                                                " Eliminate backwards-compatability
set number                                                      " Enable line numbers
set ruler                                                       " Turn on the ruler
set backspace=2                                                 " Fixes some backspace issues
set t_Co=256                                                    " 256-bit colours
set background=dark
colorscheme predawn                                             " Set the colour scheme
set guifont=Inconsolata\ for\ Powerline:h14                     " Set font to work with airline
set mouse=a                                                     " Enables the ability to use mouse
set ignorecase                                                  " ignore case when searching
set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab     " use 4 Space characters for each indent
set nowrap
set list                                                        " show trailing whitespace
set listchars=tab:▸\ ,trail:.
set clipboard=unnamed
set history=1000                                                " remember more commands and search history
set undolevels=1000                                             " remembers many levels of undo
set wildignore+=*.swp,*.bak,*.pyc,*.class
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.idea/*,*/.DS_Store,*/vendor
set title
set incsearch
highlight Normal ctermbg=Black
syntax on                                                       " Syntax highlighting

" Key map settings
nnoremap <leader>q :NERDTree<CR>
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
" Disable the arrow keys to force me to use HJKL
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
" Set ctrl+t to open a new tab
map <C-t> <Esc>:tabnew<CR>

" -------------------
" PLUGIN CONFIGURATION
" -------------------
" Vim-airline configuration
set laststatus=2
let g:airline_theme             = 'powerlineish'
let g:airline_powerline_fonts   = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0

" NERDTree Configuration:
" set autochdir
let NERDTreeChDirMode=2

" Emmet Configuration
let g:user_emmet_leader_key='<leader>y'

" ctrl-p Configuration
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = 'ra'

" NeoComplete Configuration
let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
