cask_args appdir: "/Applications"
tap "neovim/neovim"

brew "coreutils"
brew "ctags"
brew "dockutil"      # dock management
brew "fzy"
brew "git"
brew "git-lfs"
brew "gnupg2"
brew "neovim"
brew "openssl"
brew "pinentry-mac"
brew "python3"
brew "rbenv"         # tmux
brew "ruby-build"    # tmux
brew "ripgrep"
brew "yarn"

cask "1password6"
cask "alacritty"
cask "bartender"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "gpg-suite"
cask "istat-menus"
cask "keepingyouawake"
cask "mailspring"
cask "numi"
cask "spotify"

mas "BetterSnapTool", id: 417375580
