export LANG=en_US.UTF-8

# Default PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin"
export PATH=${PATH}:~/.composer/vendor/bin

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
  PATH="$HOME/.bin:$PATH"
fi

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Sets my default editor
export EDITOR='vim'
