# Oh-My-Zsh Configuration
ZSH_THEME="smith"              # Set name of the theme to load.
COMPLETION_WAITING_DOTS="true"  # Display red dots whilst waiting for completion.
plugins=(brew docker git node tmuxinator tmux)

# Language Preferences
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Setup PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin:$PATH"
export PATH=${PATH}:~/.composer/vendor/bin
if [ -d "$HOME/.bin" ]; then # Include private bin if exists
  PATH="$HOME/.bin:$PATH"
fi

# Set correct TERM for plain shell and tmux
export TERM='xterm-256color'

# Need that neovim love
export EDITOR='nvim'
export VISUAL='nvim'
alias vim="nvim"

# OS dependent configurations
# darwin = osx
if [[ $OSTYPE =~ "darwin" ]]; then

  # Android SDK Location
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

  # JAVA HOME
  export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

  # Fixes some bug in Tmux on MaxOS Sierra
  export EVENT_NOKQUEUE=1

  # Change the default location for Caskroom apps to symlink to
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"

  # Flush Directory Service cache
  alias flush="dscacheutil -flushcache"

  # File size
  alias fs="stat -f \"%z bytes\""

  # Empty the Trash on all mounted volumes and the main HDD
  alias emptyTrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

  # Hide/show all desktop icons (useful when presenting)
  alias hideDesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showDesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

  # Shows and Hides hidden files
  alias showHiddenFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
  alias hideHiddenFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

  # Some quick and dirty tmux management
  alias mux='tmux new -A -s basic'

  # Get gpg-agent to work on osx
  #eval $(gpg-agent --daemon)
  export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
  GPG_TTY=$(tty)
  export GPG_TTY
  if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
  fi

elif [[ $OSTYPE == "linux-gnu" ]]; then

fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
