##############################
# Lets make some PATH variables
##############################
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Default PATH
export PATH="/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin"

# Android SDK Location
export ANDROID_HOME=$HOME/Dev/android-sdk-macosx
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Composer applications
export PATH=${PATH}:~/.composer/vendor/bin

# JAVA HOME
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

# devkitARM Development
export DEVKITPRO=/Users/anthony/devkitPro
export DEVKITARM=${DEVKITPRO}/devkitARM

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
  PATH="$HOME/.bin:$PATH"
fi


##############################
# OH MY ZSH Configuration
##############################
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="remy-customized"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git sublime)

source $ZSH/oh-my-zsh.sh

##############################
# Aliases
##############################
# Remove all items safely, to Trash (`brew install trash`).
# Doesn't work with symbolic links.
# alias rm='trash'

# Enables the use of macvim within the terminal
alias vim='/usr/local/Cellar/macvim/HEAD/bin/mvim -v'

# Too lazy to type
alias bcit='cd ~/Dropbox/BCIT/'

# Lock current session and proceed to the login screen.
alias lock='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# Sniff network info.
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"

# Shows and Hides hidden files
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'


##############################
# Various Other Configurations
##############################
# Enable rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# 'thefuck' configuration
eval $(thefuck --alias)

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# added by .net framework
[ -s "$HOME/.dnx/dnvm/dnvm.sh" ] && . "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm

source /usr/local/lib/dnx/bin/dnvm.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
