alias flush='dscacheutil -flushcache' # Flush Directory Service cache
alias fs='stat -f \"%z bytes\"'   # Get friendly formatted filesize
alias emptyTrash='sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash' # includes mounted volumes
alias lock="/System/Library/CoreServices/\"Menu Extras\"/User.menu/Contents/Resources/CGSession -suspend"
alias show='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hide='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias showDesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'
alias hideDesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias copyssh="pbcopy < $HOME/.ssh/id_rsa.pub"
